//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanEditor_Plepor.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstline
    {
        public string LineCode { get; set; }
        public string LineDesc { get; set; }
        public string ProcessCode { get; set; }
        public string LineColor { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public int UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public int CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Resv1 { get; set; }
        public string Resv2 { get; set; }
        public string Resv3 { get; set; }
        public Nullable<decimal> Resv4 { get; set; }
        public Nullable<decimal> Resv5 { get; set; }
        public Nullable<decimal> Resv6 { get; set; }
        public Nullable<decimal> Resv7 { get; set; }
        public Nullable<decimal> Resv8 { get; set; }
        public Nullable<decimal> Resv9 { get; set; }
        public Nullable<System.DateTime> Resv10 { get; set; }
        public Nullable<System.DateTime> Resv11 { get; set; }
        public Nullable<System.DateTime> Resv12 { get; set; }
        public Nullable<int> SortSeq { get; set; }
        public string LocCode { get; set; }
    }
}
