//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanEditor_Plepor.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class prgDownTimeDetail
    {
        public string WorkDate { get; set; }
        public int ShiftID { get; set; }
        public int ProdID { get; set; }
        public int LineID { get; set; }
        public string DownID { get; set; }
        public Nullable<int> DownTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
