//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanEditor_Plepor.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class prgproductionresult
    {
        public string ProductionResultCode { get; set; }
        public string ProductionCode { get; set; }
        public string DONo { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public Nullable<decimal> OKQty { get; set; }
        public Nullable<decimal> NGQty { get; set; }
        public string ItemCode { get; set; }
        public string TypeCode { get; set; }
        public string LotNo { get; set; }
        public string StrLoc { get; set; }
        public string ComLoc { get; set; }
        public Nullable<int> PlanStatus { get; set; }
        public Nullable<int> ConsumpStatus { get; set; }
        public Nullable<int> ConsumpFlag { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Resv1 { get; set; }
        public string Resv2 { get; set; }
        public string Resv3 { get; set; }
        public Nullable<decimal> Resv4 { get; set; }
        public Nullable<decimal> Resv5 { get; set; }
        public Nullable<decimal> Resv6 { get; set; }
        public Nullable<decimal> Resv7 { get; set; }
        public Nullable<decimal> Resv8 { get; set; }
        public Nullable<decimal> Resv9 { get; set; }
        public Nullable<System.DateTime> Resv10 { get; set; }
        public Nullable<System.DateTime> Resv11 { get; set; }
        public Nullable<System.DateTime> Resv12 { get; set; }
        public int DelFlag { get; set; }
        public string ResultTime { get; set; }
        public Nullable<int> StartBoxNo { get; set; }
        public Nullable<int> EndBoxNo { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> LineID { get; set; }
        public string Operator { get; set; }
    }
}
