//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanEditor_Plepor.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class prgproductionorder
    {
        public string ProductionCode { get; set; }
        public string DONo { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public Nullable<decimal> PlanQty { get; set; }
        public Nullable<decimal> RemainQty { get; set; }
        public string ItemCode { get; set; }
        public string TypeCode { get; set; }
        public Nullable<int> PlanStatus { get; set; }
        public Nullable<int> PrintF { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string LineCode { get; set; }
        public string Resv1 { get; set; }
        public string Resv2 { get; set; }
        public string Resv3 { get; set; }
        public Nullable<decimal> Resv4 { get; set; }
        public Nullable<decimal> Resv5 { get; set; }
        public Nullable<decimal> Resv6 { get; set; }
        public Nullable<decimal> Resv7 { get; set; }
        public Nullable<decimal> Resv8 { get; set; }
        public Nullable<decimal> Resv9 { get; set; }
        public Nullable<System.DateTime> Resv10 { get; set; }
        public Nullable<System.DateTime> Resv11 { get; set; }
        public Nullable<System.DateTime> Resv12 { get; set; }
        public Nullable<decimal> ConfirmFlag { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> POSLevel { get; set; }
        public string PPOSCode { get; set; }
        public string PreviousNo { get; set; }
        public int OutsourceFlag { get; set; }
        public Nullable<System.DateTime> ResultStartDate { get; set; }
        public string ResultStartTime { get; set; }
        public Nullable<int> CntBoxNo { get; set; }
        public Nullable<int> ResultSeqNo { get; set; }
        public Nullable<decimal> ResvQty { get; set; }
        public Nullable<decimal> AbleQty { get; set; }
    }
}
