//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanEditor.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstcalendardetail
    {
        public decimal CalNo { get; set; }
        public System.DateTime CalDate { get; set; }
        public Nullable<decimal> HolidayFlag { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
