//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanEditor.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstitem
    {
        public string ItemCode { get; set; }
        public string TypeCode { get; set; }
        public string ItemName { get; set; }
        public string AbbName { get; set; }
        public string ItemType { get; set; }
        public Nullable<decimal> LotFlag { get; set; }
        public string UnitCode { get; set; }
        public string StrLoc { get; set; }
        public string ComLoc { get; set; }
        public Nullable<decimal> ProdLT { get; set; }
        public Nullable<decimal> ReqDec { get; set; }
        public Nullable<decimal> MRPFlag { get; set; }
        public string BOI { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> ConsumpFlag { get; set; }
        public string DefaultSupplier { get; set; }
        public Nullable<int> DeliUnit { get; set; }
        public Nullable<decimal> QtyPerDeli { get; set; }
        public Nullable<int> PurchaseStaff { get; set; }
        public string GroupItem { get; set; }
        public Nullable<int> BOMSeq { get; set; }
        public string ConvertUnit { get; set; }
        public Nullable<decimal> ConvertValue { get; set; }
        public string Resv1 { get; set; }
        public string Resv2 { get; set; }
        public string Resv3 { get; set; }
        public Nullable<decimal> Resv4 { get; set; }
        public Nullable<decimal> Resv5 { get; set; }
        public Nullable<decimal> Resv6 { get; set; }
        public Nullable<decimal> Resv7 { get; set; }
        public Nullable<decimal> Resv8 { get; set; }
        public Nullable<decimal> Resv9 { get; set; }
        public Nullable<System.DateTime> Resv10 { get; set; }
        public Nullable<System.DateTime> Resv11 { get; set; }
        public Nullable<System.DateTime> Resv12 { get; set; }
        public Nullable<int> ExpireTerm { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public int Boxsize { get; set; }
        public Nullable<int> sBoxsize { get; set; }
        public Nullable<int> DefaultLineCode { get; set; }
        public Nullable<int> Ability { get; set; }
        public Nullable<int> ProdType { get; set; }
        public string MCNo { get; set; }
        public string WireColor { get; set; }
        public Nullable<decimal> Length { get; set; }
    }
}
