//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanEditor.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstline_Marunix
    {
        public int LineID { get; set; }
        public string LineName { get; set; }
        public Nullable<int> ProdID { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public int CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Resv1 { get; set; }
        public string Resv2 { get; set; }
        public string Resv3 { get; set; }
        public Nullable<decimal> Resv4 { get; set; }
        public Nullable<decimal> Resv5 { get; set; }
        public Nullable<decimal> Resv6 { get; set; }
        public Nullable<decimal> Resv7 { get; set; }
        public Nullable<decimal> Resv8 { get; set; }
        public Nullable<decimal> Resv9 { get; set; }
        public Nullable<System.DateTime> Resv10 { get; set; }
        public Nullable<System.DateTime> Resv11 { get; set; }
        public Nullable<System.DateTime> Resv12 { get; set; }
        public Nullable<int> DefStaffQtyD { get; set; }
        public Nullable<int> DefStaffQtyN { get; set; }
        public Nullable<int> DefStaffQtyHD { get; set; }
        public Nullable<int> DefStaffQtyHN { get; set; }
        public Nullable<int> WorkQty { get; set; }
        public Nullable<decimal> TargetD { get; set; }
        public Nullable<decimal> TargetN { get; set; }
    }
}
