//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanEditor.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstlinecalendar
    {
        public System.DateTime CalDate { get; set; }
        public string CalText { get; set; }
        public string Remark { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
